development:
  api_user: user
  api_password: pass
  redis:
    host: localhost
    port: 6379
    password:
production:
  api_user: prod
  api_password: prod
test:
  api_user: test
  api_password: test
